name: Crear y subir página a GitHub Pages

on: 
  workflow_dispatch: # Permite activarlo manualmente
  schedule:
    - cron: '0 9 * * *' # Ejecuta cada 9:00 UTC de cada dia

  permissions:
    contents: read
    pages: write
    id-token: write

  concurrency:
    group: "pages"
    cancel-in-progress: false

  jobs:
    count-commits:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Obtener últimos commits
          run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago')" >> $GITHUB_ENV

        - name: Cantidad de commits
          run: echo "Se tiene $NEW_COMMIT_COUNT commits"

      outputs:
        count: ${{ env.NEW_COMMIT_COUNT }}

    build:
      needs: count-commits

      if: needs.count-commits.outputs.count > 0
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Creando la página estatica
          uses: addnab/docker-run-action@v3
          with: 
            image: juanbiancuzzo/obsidian-static-site:latest
            options: -v ${{ github.workspace }}:/usr/src/app/content
            run: sh -c ./start.sh

        - name: Subir artifacts
          uses: actions/upload-pages-artifact@v2
          with:
            path: public
    
    deploy:
      needs: build

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest

      steps:
        - name: Subiendo a GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
